#!/bin/bash

err=0
trap 'err=1' ERR

rm -rf /srv
git clone https://github.com/AntonYudintsev/tryitonline.git /srv
#git -C /srv fetch origin pull/73/head:AntonYudintsev
#git -C /srv checkout AntonYudintsev

exit "$err"

source private/config

if [[ ! -z $TryItOnlineCommit ]]; then
    git -C /srv checkout $TryItOnlineCommit
fi

exit "$err"
